export const SET_MAP_REF = "SET_MAP_REF";
export const SET_MAP_STATE = "SET_MAP_STATE";
export const SET_ROUTE_BLOCK = "SET_ROUTE_BLOCK";
export const SET_DISTANCE_FROM_ROUTE = "SET_DISTANCE_FROM_ROUTE";

export const SET_USE_CASE = "SET_USE_CASE";
export const TOGGLE_CLUSTERING = "TOGGLE_CLUSTERING";

export const FETCH_ALL_STATIONS_WITHIN_POLYGON_IS_LOADING = "FETCH_ALL_STATIONS_WITHIN_POLYGON_IS_LOADING";
export const FETCH_ALL_STATIONS_WITHIN_POLYGON_HAS_FAILED = "FETCH_ALL_STATIONS_WITHIN_POLYGON_HAS_FAILED";
export const FETCH_ALL_STATIONS_WITHIN_POLYGON_SUCCESS = "FETCH_ALL_STATIONS_WITHIN_POLYGON_SUCCESS";

export const FILTER_STATIONS_BY_TYPES = "FILTER_STATIONS_BY_TYPES";

export const FETCH_CHOOSEN_LAND_IS_LOADING = "FETCH_CHOOSEN_LAND_IS_LOADING";
export const FETCH_CHOOSEN_LAND_HAS_FAILED = "FETCH_CHOOSEN_LAND_HAS_FAILED";
export const FETCH_CHOOSEN_STATION_SUCCESS = "FETCH_CHOOSEN_STATION_SUCCESS";
export const SET_CHOOSEN_STATION = "SET_CHOOSEN_STATION";

export const FETCH_ALL_PARKING_LOTS_NEAR_STATION_IS_LOADING = "FETCH_ALL_PARKING_LOTS_NEAR_STATION_IS_LOADING";
export const FETCH_ALL_PARKING_LOTS_NEAR_STATION_HAS_FAILED = "FETCH_ALL_PARKING_LOTS_NEAR_STATION_HAS_FAILED";
export const FETCH_ALL_PARKING_LOTS_NEAR_STATION_SUCCESS = "FETCH_ALL_PARKING_LOTS_NEAR_STATION_SUCCESS";
export const SET_ALL_PARKING_LOTS_NEAR_STATION = "SET_ALL_PARKING_LOTS_NEAR_STATION";

export const TOGGLE_ROUTING = "TOGGLE_ROUTING";
export const SET_ROUTE = "SET_ROUTE";

export const SET_ON_MAP_CLICK = "SET_ON_MAP_CLICK";

export const FETCH_STATIONS_NEAR_ROUTE_IS_LOADING = "FETCH_STATIONS_NEAR_ROUTE_IS_LOADING";
export const FETCH_STATIONS_NEAR_ROUTE_HAS_FAILED = "FETCH_STATIONS_NEAR_ROUTE_HAS_FAILED";
export const FETCH_STATIONS_NEAR_ROUTE_SUCCESS = "FETCH_STATIONS_NEAR_ROUTE_SUCCESS";
export const SET_STATIONS_NEAR_ROUTE = "SET_STATIONS_NEAR_ROUTE";

export const FETCH_STATION_AREALS_IS_LOADING = "FETCH_STATION_AREALS_IS_LOADING";
export const FETCH_STATION_AREALS_HAS_FAILED = "FETCH_STATION_AREALS_HAS_FAILED";
export const FETCH_STATION_AREALS_SUCCESS = "FETCH_STATION_AREALS_SUCCESS";


export const SET_SEARCH_ADDRESS = "SET_SEARCH_ADDRESS";
export const SET_SEARCH_BOUNDS = "SET_SEARCH_BOUNDS";
export const SET_SEARCH_RADIUS = "SET_SEARCH_RADIUS";

export const FETCH_LANDS_IS_LOADING = "FETCH_LANDS_IS_LOADING";
export const FETCH_LANDS_HAS_FAILED = "FETCH_LANDS_HAS_FAILED";
export const FETCH_LANDS_SUCCESS = "FETCH_LANDS_SUCCESS";


